"""Deterministic, quote-aware paper execution for historical replay.

This module never submits an order to a broker.  It models the first visible
top-of-book quote at or after an order's latency-adjusted eligibility time.
Prices remain integer micro-dollars until the final fill/cost accounting.
"""

from __future__ import annotations

from dataclasses import dataclass

from .types import Fill, OrderRequest


@dataclass(frozen=True)
class ExecutionConfig:
    latency_ns: int = 0
    fixed_slippage_micro: int = 0
    slippage_bps: float = 0.0
    commission_per_trade: float = 0.0
    commission_per_share: float = 0.0
    minimum_commission: float = 0.0

    @classmethod
    def from_ms(cls, latency_ms: float = 0.0, **kwargs) -> "ExecutionConfig":
        return cls(latency_ns=int(round(latency_ms * 1_000_000)), **kwargs)

    def __post_init__(self) -> None:
        if self.latency_ns < 0:
            raise ValueError("latency_ns must be non-negative")
        if self.fixed_slippage_micro < 0 or self.slippage_bps < 0:
            raise ValueError("slippage must be non-negative")
        if min(self.commission_per_trade, self.commission_per_share, self.minimum_commission) < 0:
            raise ValueError("commission settings must be non-negative")


class ExecutionSimulator:
    """Fill hypothetical orders against the exact replayed quote features."""

    def __init__(self, config: ExecutionConfig | None = None) -> None:
        self.config = config or ExecutionConfig()
        self._next_order_id = 1
        self._pending: list[OrderRequest] = []
        self.unfilled_orders: list[OrderRequest] = []

    @property
    def pending_orders(self) -> tuple[OrderRequest, ...]:
        return tuple(self._pending)

    def new_order_id(self) -> int:
        value = self._next_order_id
        self._next_order_id += 1
        return value

    def submit(
        self,
        order: OrderRequest,
        *,
        timestamp_ns: int,
        feature=None,
        is_quote: bool = False,
        force_immediate: bool = False,
    ) -> list[Fill]:
        """Queue an order, or fill it immediately if this event is eligible.

        A candidate generated by a trade waits for a subsequent quote even
        with zero latency.  A candidate generated by a quote may use that
        quote, which is the deterministic ``T + 0`` interpretation.
        """

        if order.quantity < 1:
            raise ValueError("order quantity must be positive")
        if force_immediate:
            eligible = timestamp_ns
        else:
            eligible = order.order_timestamp_ns + self.config.latency_ns
        if eligible != order.eligible_timestamp_ns and not force_immediate:
            order = OrderRequest(**{**order.__dict__, "eligible_timestamp_ns": eligible})
        if is_quote and feature is not None and eligible <= timestamp_ns:
            fill = self._make_fill(order, timestamp_ns, feature)
            if fill is not None:
                return [fill]
        self._pending.append(order)
        return []

    def on_quote(self, timestamp_ns: int, feature) -> list[Fill]:
        """Attempt pending orders in submission order on the current quote."""

        fills: list[Fill] = []
        remaining: list[OrderRequest] = []
        for order in self._pending:
            if order.symbol_id != feature.symbol_id or order.eligible_timestamp_ns > timestamp_ns:
                remaining.append(order)
                continue
            fill = self._make_fill(order, timestamp_ns, feature)
            if fill is None:
                remaining.append(order)
            else:
                fills.append(fill)
        self._pending = remaining
        return fills

    def flush(self) -> list[OrderRequest]:
        """Mark orders left at the end of replay as unfilled."""

        self.unfilled_orders.extend(self._pending)
        pending = list(self._pending)
        self._pending.clear()
        return pending

    def _make_fill(self, order: OrderRequest, timestamp_ns: int, feature) -> Fill | None:
        if feature.symbol_id != order.symbol_id or not getattr(feature, "spread_valid", True):
            return None
        reference_price = self._reference_price(order, feature)
        if reference_price is None or reference_price <= 0:
            return None
        fill_price = self._apply_slippage(reference_price, order.side)
        commission = self._commission(order.quantity)
        return Fill(
            order_id=order.order_id,
            symbol_id=order.symbol_id,
            side=order.side,
            purpose=order.purpose,
            position_direction=order.position_direction,
            quantity=order.quantity,
            timestamp_ns=timestamp_ns,
            reference_price=reference_price,
            fill_price=fill_price,
            commission=commission,
            candidate_timestamp_ns=order.candidate_timestamp_ns,
            candidate_reason_bits=order.candidate_reason_bits,
            candidate_score=order.candidate_score,
            exit_reason=order.exit_reason,
            eligible_timestamp_ns=order.eligible_timestamp_ns,
            candidate_sequence=order.candidate_sequence,
            candidate_feature=order.candidate_feature,
        )

    @staticmethod
    def _reference_price(order: OrderRequest, feature) -> int | None:
        # Buy-to-open long and sell-to-close short consume the ask.  The other
        # two transitions consume the bid.  No midpoint or last trade is used.
        if order.side == "buy":
            return feature.ask_price if feature.ask_price > 0 and feature.ask_quantity > 0 else None
        if order.side == "sell":
            return feature.bid_price if feature.bid_price > 0 and feature.bid_quantity > 0 else None
        raise ValueError(f"unsupported order side: {order.side!r}")

    def _apply_slippage(self, reference_price: int, side: str) -> int:
        bps = int(reference_price * self.config.slippage_bps / 10_000.0)
        adverse = self.config.fixed_slippage_micro + bps
        return reference_price + adverse if side == "buy" else max(1, reference_price - adverse)

    def _commission(self, quantity: int) -> float:
        raw = self.config.commission_per_trade + self.config.commission_per_share * quantity
        if raw == 0:
            return 0.0
        return max(self.config.minimum_commission, raw)
