`ifndef PROTOCOL_DEFS_SVH
`define PROTOCOL_DEFS_SVH

`define PACKET_BYTES 32
`define PACKET_BITS  256

`define PROTOCOL_SYNC_VERSION 8'hA1

`define MSG_MARKET_QUOTE 8'h01
`define MSG_MARKET_TRADE 8'h02
`define MSG_CONTROL      8'h03
`define MSG_HEARTBEAT    8'h04
`define MSG_SIGNAL       8'h05
`define MSG_STATUS       8'h06
`define MSG_LOOPBACK     8'h07

`define STATUS_OK             8'h01
`define STATUS_BAD_SYNC       8'hE1
`define STATUS_BAD_CHECKSUM   8'hE2
`define STATUS_BAD_TYPE       8'hE3
`define STATUS_BAD_SYMBOL     8'hE4
`define STATUS_DUPLICATE_SEQ  8'hE5
`define STATUS_STALE_SEQ      8'hE6
`define STATUS_BAD_SIDE       8'hE7
`define STATUS_BAD_CONTROL    8'hE8
`define STATUS_CONFIG_BUSY    8'hE9

// Runtime strategy-control subcommands. Control packets reuse the fixed
// 32-byte packet layout: symbol_id is bytes 2..3, data64 is bytes 12..19,
// data32 is bytes 20..23, subcommand is byte 24, and flags are bytes 29..30.
`define CONTROL_SET_GLOBAL_FLAGS       8'h10
`define CONTROL_SET_LONG_MOMENTUM      8'h11
`define CONTROL_SET_SHORT_MOMENTUM     8'h12
`define CONTROL_SET_LONG_VWAP_DELTA    8'h13
`define CONTROL_SET_SHORT_VWAP_DELTA   8'h14
`define CONTROL_SET_LONG_IMBALANCE     8'h15
`define CONTROL_SET_SHORT_IMBALANCE    8'h16
`define CONTROL_SET_MAX_SPREAD         8'h17
`define CONTROL_SET_MIN_VOLUME         8'h18
`define CONTROL_SET_COOLDOWN           8'h19
`define CONTROL_SET_SYMBOL_ENABLE      8'h1A
`define CONTROL_CLEAR_SYMBOL_STATE     8'h1B
`define CONTROL_GET_CONFIG             8'h1C

`define SIGNAL_NONE            2'd0
`define SIGNAL_LONG_CANDIDATE  2'd1
`define SIGNAL_SHORT_CANDIDATE 2'd2

`define SIGNAL_REASON_MOMENTUM_PASS    16'h0001
`define SIGNAL_REASON_VWAP_DELTA_PASS  16'h0002
`define SIGNAL_REASON_IMBALANCE_PASS   16'h0004
`define SIGNAL_REASON_SPREAD_PASS      16'h0008
`define SIGNAL_REASON_VOLUME_PASS      16'h0010
`define SIGNAL_REASON_LONG_DIRECTION   16'h0020
`define SIGNAL_REASON_SHORT_DIRECTION  16'h0040
`define SIGNAL_REASON_COOLDOWN_ACTIVE  16'h0080
`define SIGNAL_REASON_INVALID_FEATURE  16'h0100
`define SIGNAL_REASON_SYMBOL_DISABLED  16'h0200
`define SIGNAL_REASON_STRATEGY_DISABLED 16'h0400
`define SIGNAL_REASON_LONG_DISABLED    16'h0800
`define SIGNAL_REASON_SHORT_DISABLED   16'h1000
`define SIGNAL_REASON_SUPPRESSED       16'h2000

`endif
